In [8]:
import gymnasium as gym
import numpy as np

In [9]:
class GridWorld:
    def __init__(self):
        self.size = 5

        self.start = (0,0)
        self.goal = (4,4)

        self.obstracles = {
            (1,1),
            (1,3),
            (2,3),
            (3,1)
        }

        self.agent = self.start

    def reset(self):
        self.agent = self.start
        return self.agent

    def step(self,action):
        row, col = self.agent

        if action == 0:       # вверх
            new_position = (row - 1, col)

        elif action == 1:     # вправо
            new_position = (row, col + 1)

        elif action == 2:     # вниз
            new_position = (row + 1, col)

        elif action == 3:     # влево
            new_position = (row, col - 1)

        if not (0<=new_position[0] <self.size and 0<=new_position[1]< self.size):
            return self.agent, -0.5, False

        if new_position in self.obstracles:
            return self.agent, -0.5 ,False

        self.agent = new_position

        if self.agent == self.goal:
            return self.agent,1.0, True

        return self.agent,-0.04,False



In [10]:
def chose_action(Q, state, epsilon):

    if np.random.random() < epsilon:
        # Исследование
        return np.random.randint(4)

    else:
        # Используем лучшее известное действие
        return np.argmax(Q[state])

In [11]:
env = GridWorld()

state = env.reset()

print(state)

(0, 0)


In [12]:
actions = [
    1,  # вправо
    1,  # вправо
    1,  # вправо
    1,  # вправо
    2,  # вниз
    2,
    2,
    2
]

for action in actions:
    state, reward ,done = env.step(action)
    print(
        "state:", state,
        "reward:", reward,
        "done:", done
    )

    if done:
        break


state: (0, 1) reward: -0.04 done: False
state: (0, 2) reward: -0.04 done: False
state: (0, 3) reward: -0.04 done: False
state: (0, 4) reward: -0.04 done: False
state: (1, 4) reward: -0.04 done: False
state: (2, 4) reward: -0.04 done: False
state: (3, 4) reward: -0.04 done: False
state: (4, 4) reward: 1.0 done: True


In [13]:
gamma= 0.95
alpha= 0.1
eps = 1.0
eps_step = 0.05
eps_end = 0.05
eps_decay = 0.995

In [14]:
Q = np.zeros((5,5,4))#5,5- rows,col ,last - action
# Q[state, action] = Q[state, action] + alpha * (
#     reward + gamma * max(Q[next_state]) - Q[state, action]
# )

for epoch in range(200):

    state = env.reset()
    done = False

    while not done:
        action = chose_action(Q, state, eps)

        next_state, reward, done = env.step(action)

        if done:
            target = reward
        else:
            target = reward + gamma * np.max(Q[next_state])

        Q[state, action] += alpha * (target - Q[state, action])


        state = next_state

    eps = max(eps_end, eps * eps_decay)

    print(f"Episode {epoch} complete")

Episode 0 complete
Episode 1 complete
Episode 2 complete
Episode 3 complete
Episode 4 complete
Episode 5 complete
Episode 6 complete
Episode 7 complete
Episode 8 complete
Episode 9 complete
Episode 10 complete
Episode 11 complete
Episode 12 complete
Episode 13 complete
Episode 14 complete
Episode 15 complete
Episode 16 complete
Episode 17 complete
Episode 18 complete
Episode 19 complete
Episode 20 complete
Episode 21 complete
Episode 22 complete
Episode 23 complete
Episode 24 complete
Episode 25 complete
Episode 26 complete
Episode 27 complete
Episode 28 complete
Episode 29 complete
Episode 30 complete
Episode 31 complete
Episode 32 complete
Episode 33 complete
Episode 34 complete
Episode 35 complete
Episode 36 complete
Episode 37 complete
Episode 38 complete
Episode 39 complete
Episode 40 complete
Episode 41 complete
Episode 42 complete
Episode 43 complete
Episode 44 complete
Episode 45 complete
Episode 46 complete
Episode 47 complete
Episode 48 complete
Episode 49 complete
Episode 50

In [15]:
for row in range(5):
    for col in range(5):
        print(f"State ({row}, {col}): {Q[row, col]}")

State (0, 0): [-1.0862749 -1.0862749 -1.0862749 -1.0862749]
State (0, 1): [-0.76533588 -0.76533588 -0.76533588 -0.76533588]
State (0, 2): [-1.44982588 -1.44982588 -1.44982588 -1.44982588]
State (0, 3): [-1.63877441 -1.63877441 -1.63877441 -1.63877441]
State (0, 4): [0. 0. 0. 0.]
State (1, 0): [-1.29772561 -1.29772561 -1.29772561 -1.29772561]
State (1, 1): [-1.07986134 -1.07986134 -1.07986134 -1.07986134]
State (1, 2): [-1.00778684 -1.00778684 -1.00778684 -1.00778684]
State (1, 3): [-1.31358973 -1.31358973 -1.31358973 -1.31358973]
State (1, 4): [0. 0. 0. 0.]
State (2, 0): [-1.60115848 -1.60115848 -1.60115848 -1.60115848]
State (2, 1): [-1.40634076 -1.40634076 -1.40634076 -1.40634076]
State (2, 2): [-1.01241803 -1.01241803 -1.01241803 -1.01241803]
State (2, 3): [-0.80818446 -0.80818446 -0.80818446 -0.80818446]
State (2, 4): [0. 0. 0. 0.]
State (3, 0): [-2.0586924 -2.0586924 -2.0586924 -2.0586924]
State (3, 1): [-0.04 -0.04 -0.04 -0.04]
State (3, 2): [-1.66374807 -1.66374807 -1.66374807 -

In [16]:
print(np.argmax(Q, axis=2))

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [18]:
env.reset()

state = env.reset()
action = 1

print("agent:", env.agent)
print("state:", state)

next_state, reward, done = env.step(action)

print("next_state:", next_state)
print("reward:", reward)

agent: (0, 0)
state: (0, 0)
next_state: (0, 1)
reward: -0.04


In [19]:
Q = np.zeros((5, 5, 4))

target = reward + gamma * np.max(Q[next_state])

Q[state, action] += alpha * (target - Q[state, action])

print(Q[state])

[0. 0. 0. 0.]
